version: '3.8'

services:
  # Database Service
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flash-network

  # Redis Service (Redisson Lock and Idempotency store)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flash-network

  # Kafka Zookeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - flash-network

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - flash-network

  # Wallet Core Microservice
  wallet-core:
    image: yatharthlashkari/wallet-core-0.0.1-snapshot
    container_name: wallet-core
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - postgres-db
      - redis
      - kafka
    networks:
      - flash-network

  # Audit Worker Microservice
  audit-worker:
    image: yatharthlashkari/audit-worker-0.0.1-snapshot
    container_name: audit-worker
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - postgres-db
      - kafka
    networks:
      - flash-network

  # API Gateway Microservice
  api-gateway:
    image: yatharthlashkari/api-gateway-0.0.1-snapshot
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - WALLET_CORE_URI=http://wallet-core:8081
    depends_on:
      - wallet-core
    networks:
      - flash-network

volumes:
  postgres_data:
  redis_data:

networks:
  flash-network:
    driver: bridge
